"use client"
import "./globals.css";
import Navbar from "./(website)/homepage/components/Navbar/Navbar";
import { usePathname } from "next/navigation";
import Footer from "@/components/Footer";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Check if the current route starts with '/dashboard'
  const isDashboardRoute = pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className="">
        {/* Show Navbar and Footer only if not on dashboard routes */}
        {!isDashboardRoute && <Navbar />}
        {children}
        {!isDashboardRoute && <Footer />}
      </body>
    </html>
  );
}
